---
_id: e6495250-2e5a-11e9-8891-e51288815d8e
metadata:
  author:
    first: Xueyang
    last: Wu
    email: wuxueyang@ufl.edu
    github_id: xueyang94
  timestamp: '11 February, 2019'
  summary: MOOSE framework
  implementation:
    name: moose
    repo:
      url: 'https://github.com/xueyang94/chimad2_Oswald_Ripening_a'
      version: 3e22587688ef18ceaa459f16e1e9222a145909d5
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '3'
    cores: '64'
    nodes: '2'
benchmark:
  id: 2a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '2507'
        sim_time: '604800'
  - name: memory_usage
    values:
      - unit: KB
        value: '12531700'
  - name: free_energy
    url: >-
      https://raw.githubusercontent.com/xueyang94/chimad2_Oswald_Ripening_a/master/periodic_square_csv.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: 'total free energy versus simulation time '
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1549930356
