---
language: python
install:
  - sudo apt-get update
  - sudo apt-get install ruby ruby-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -y -n test-environment python=3.5
  - source activate test-environment
  - conda install -q -y -n test-environment jupyter pillow numpy toolz pytest bokeh matplotlib scikit-image flake8
  - conda install nb_conda nb_conda_kernels nb_anacondacloud
  - pip install progressbar2 pykwalify pylint nbval vega
  - jupyter nbextension enable vega --py
  - unset VIRTUAL_ENV
  - gem install jekyll jekyll-coffeescript html-proofer
script:
  - pylint _data/*.py
  - flake8 _data/*.py
  - make simulations
  - find . -name "*.ipynb" -type f -not -path "*/.ipynb_checkpoints/*" -exec touch {} \;
  - make notebooks
  - touch _data/hexbin.yaml
  - make hexbin
  - rm -rf ./_site
  - jekyll build -d ./_site/chimad-phase-field && htmlproofer --allow-hash-href --empty-alt-ignore --checks-to-ignore ImageCheck ./_site
  - py.test --ignore=hackathon1 --ignore=benchmarks --ignore=_data --nbval --sanitize-with sanitize.cfg
