#Change this to the name of your repo
baseurl: '/chimad-phase-field'

markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  # these collections can be used later as static api endpoints
  # /<site.baseurl>/repos/fipy.json
  # is a static file for the fipy github api response
  # this is not dynamic enough.  webhoooooooks
  repos:
    output: true
  cards:
    output: true

exclude:
  - "*.ipynb"
  - "*.ipynb.raw.html"
  - vendor
  - template.ipynb.md


links:
  contributors: https://github.com/usnistgov/chimad-phase-field/graphs/contributors
  license: https://github.com/usnistgov/chimad-phase-field/blob/nist-pages/LICENSE
  repo: usnistgov/chimad-phase-field
  github: https://github.com/usnistgov/chimad-phase-field
  chat: https://gitter.im/usnistgov/chimad-phase-field
  members: https://docs.google.com/spreadsheets/d/112cDOOwzxLGbRx7yPte6HaXQgzQSXULrrVJLEmJvrKM/pubhtml?gid=764068827&single=true
  simmeta: https://github.com/usnistgov/chimad-phase-field/blob/master/_data/simulations

title: pages.nist.gov is broken go to <a href="https://usnistgov.github.com/chimad-phase-field">gh-pages</a>

#CHiMaD Phase Field <a href="https://www.github.com">link</a>

gems: [jekyll-coffeescript]
