---
_id: 39f2e6b0-9c10-11e8-995f-5178b29ab3fb
benchmark:
  id: 2b
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '100000'
    wall_time: '7180'
- name: memory_usage
  values:
  - unit: KB
    value: '1664626'
- description: Data for benchmark 2b
  format:
    parse:
      time: number
      total_energy: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.total_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/78424733cb6f3a1379ec55fe49d64b00/raw/aa3918c8e919dd1379bbb54746e60992430553de/MOOSE_FH_2b.csv
date: 1533845414
metadata:
  author:
    email: fhilty@ufl.edu
    first: Floyd
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: '0'
    cores: '8'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/2b.i
      version: a001b86
  summary: Results for benchmark 2b
  timestamp: 9 August, 2018
