---
_id: 62846a00-e674-11e8-8f15-8b93b5c96d99
metadata:
  author:
    first: Ivan
    last: Yashchuk
    email: ivan.yashchuk@vtt.fi
    github_id: IvanYashchuk
  timestamp: '12 November, 2018'
  summary: "PF Hub benchmark 2d with FEniCS on the cluster.\r\nTriangular mesh with ~72k cells."
  implementation:
    name: fenics
    repo:
      url: 'https://bitbucket.org/fenics-project/dolfin/'
      version: bec9fa53e5900a0dce28653cf193db5fac58255e
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '2.6'
    cores: '24'
    nodes: '1'
benchmark:
  id: 2d
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '57070'
        sim_time: '103167'
  - name: memory_usage
    values:
      - unit: KB
        value: '32641008'
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/IvanYashchuk/4fea07f6c04e7f2a67b9aabdae338cf4/raw/8de24b464483d94dab897ae5d963d310e827f171/2d_sphere_noflux.csv
    format:
      type: csv
      parse:
        time: number
        total_free_energy: number
    description: total_free_energy_fenics_2d_ivan
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_free_energy
        as: 'y'
date: 1542024818
