---
_id: 8cc6bcb0-9c0e-11e8-995f-5178b29ab3fb
benchmark:
  id: 1a
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '1000000'
    wall_time: '1244'
- name: memory_usage
  values:
  - unit: KB
    value: '1016432'
- description: Simulation data for benchmark 1a
  format:
    parse:
      time: number
      total_energy: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.total_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/af553a152a933bba5552a4eaa7313069/raw/0dba93516118065419bda950993381f04af1a879/MOOSE_FH_1a.csv
date: 1533844694
metadata:
  author:
    email: fhilty@ufl.edu
    first: Floyd
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: '0'
    cores: '8'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/1a.i
      version: a001b86
  summary: Results for benchmark 1a
  timestamp: 9 August, 2018
