---
_id: 74f7cd10-a486-11e8-9ae0-593cf187bda1
metadata:
  author:
    first: Ian
    last: Greenquist
    email: ikg5018@psu.edu
    github_id: itgreenquist
  timestamp: '29 March, 2018'
  summary: Results for benchmark 2c
  implementation:
    name: moose
    repo:
      url: 'https://github.com/itgreenquist/moose/tree/benchmark'
      version: fa4420c
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '8'
    nodes: '1'
benchmark:
  id: 2c
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '1481'
        sim_time: '597'
  - name: memory_usage
    values:
      - unit: KB
        value: '37589450'
  - name: free_energy
    url: >-
      https://raw.githubusercontent.com/itgreenquist/moose/benchmark/benchmark_uploads/prob_2/c_energy.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: Data for benchmark 2c
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1534775803
