---
_id: ff0b55e0-21f1-11eb-bfc9-bf7aa9f90ae9
metadata:
  author:
    first: Xiaoyu
    last: Guan
    email: guanxiaoyuyu@gmail.com
    github_id: xiaoyuguan
  timestamp: '2 November, 2020'
  summary: >-
    Input file and simulation result of Ostwald ripening simulation in sphere
    mesh (PFHub Benchmark problem 2d). The simulation is run by MOOSE framework.
  implementation:
    name: moose
    repo:
      url: 'https://github.com/xiaoyuguan/ostwald_spheremesh.git'
      version: fff076a763987b11d3684a5cf5cb6ad32dbc6b71
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '3'
    cores: '8'
    nodes: '1'
benchmark:
  id: 2d
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '72300'
        sim_time: '1e+06'
  - name: memory_usage
    values:
      - unit: KB
        value: '7680982.07'
  - name: free_energy
    url: >-
      https://raw.githubusercontent.com/xiaoyuguan/ostwald_spheremesh/main/peacock_run_exe_tmp_ostwald_spheremesh_Guan_out.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: total energy in the sphere mesh during time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1604860881
