---
_id: 8be412a0-ce47-11e8-b794-f95e4398131f
metadata:
  author:
    first: Stephen
    last: DeWitt
    email: stvdwtt@umich.edu
    github_id: stvdwtt
  timestamp: '12 October, 2018'
  summary: "This simulation was conducted using PRISMS-PF with quadratic elements and adaptive meshing. Forward Euler time stepping was used. This run is meant to be faster, but less accurate than 'PRISMS_PF_3a_cubic'. The tip velocity is within 0.2% of a simulation conducted with cubic elements and with the element width reduced by a factor of 1.5. To decrease the run time, all trig functions were done with single precision.\r\n\r\ndt = 0.0125\r\nmin dx = 1.875"
  implementation:
    name: prisms
    repo:
      url: 'https://github.com/stvdwtt/phaseField/tree/bm3_speed_test'
      version: b0bb19104d25f53b5f9ce90203cf0bcd46f9163c
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '3.5'
    cores: '6'
    nodes: '1'
benchmark:
  id: 3a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '48.9'
        sim_time: '1500'
  - name: memory_usage
    values:
      - unit: KB
        value: '130000'
  - name: free_energy
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm3_results_faster.csv'
    format:
      type: csv
      parse:
        time: number
        free_energy: number
    description: Free energy as a function of time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.free_energy
        as: 'y'
  - name: tip_position
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm3_results_faster.csv'
    format:
      type: csv
      parse:
        time: number
        tip_position: number
    description: Tip position as a function of time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.tip_position
        as: 'y'
  - name: solid_fraction
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/bm3_results_faster.csv'
    format:
      type: csv
      parse:
        time: number
        solid_fraction: number
    description: Solid area fraction as a function of time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.solid_fraction
        as: 'y'
  - name: phase_field_1500
    url: 'https://f000.backblazeb2.com/file/pfhub-sjd/phase_field_1500_faster.csv'
    format:
      type: csv
      parse:
        x: number
        'y': number
    description: Zero level set of the order parameter at t=1500.
    type: line
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
date: 1539366732
