---
_id: fc221f50-9c0e-11e8-995f-5178b29ab3fb
benchmark:
  id: 1b
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '1000000'
    wall_time: '1206'
- name: memory_usage
  values:
  - unit: KB
    value: '915056'
- description: Data for benchmark 1b
  format:
    parse:
      time: number
      total_energy: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.total_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/999a83b9bae0f96b446b00512b9ae5b2/raw/83228b9d49f73b7d4136d440a3c5a4d54de60d5f/MOOSE_FH_1b.csv
date: 1533844881
metadata:
  author:
    email: fhilty@ufl.edu
    first: Floyd
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: '0'
    cores: '8'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/1b.i
      version: a001b86
  summary: Results for benchmark 1b
  timestamp: 9 August, 2018
