---
benchmark:
  id: 1b
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '200000'
    wall_time: '7388'
- name: memory_usage
  values:
  - unit: KB
    value: '308224'
- description: free energy data
  format:
    parse:
      free_energy: number
      sim_time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.sim_time
    type: formula
  type: line
  url: https://ndownloader.figshare.com/files/10030003
- description: microstructure at t=0
  name: image_000
  type: image
  url: https://ndownloader.figshare.com/files/10030006
- description: microstructure at t=5,000
  name: image_005
  type: image
  url: https://ndownloader.figshare.com/files/10030009
- description: microstructure at t=10,000
  name: image_010
  type: image
  url: https://ndownloader.figshare.com/files/10030012
- description: microstructure at t=20,000
  name: image_020
  type: image
  url: https://ndownloader.figshare.com/files/10030015
- description: microstructure at t=50,000
  name: image_050
  type: image
  url: https://ndownloader.figshare.com/files/10030018
- description: microstructure at t=100,000
  name: image_100
  type: image
  url: https://ndownloader.figshare.com/files/10030021
- description: microstructure at t=120,000
  name: image_120
  type: image
  url: https://ndownloader.figshare.com/files/10071574
- description: microstructure at t=150,000
  name: image_150
  type: image
  url: https://ndownloader.figshare.com/files/10030024
- description: microstructure at t=200,000
  name: image_200
  type: image
  url: https://ndownloader.figshare.com/files/10030027
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: '1.48'
    cores: '1792'
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: threaded
  implementation:
    container_url: ''
    name: custom
    repo:
      url: https://github.com/usnistgov/hiperc
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
  simulation_name: hiperc_cuda
  summary: HiPerC spinodal decomposition result using CUDA on a Tesla P100 with 9-point
    discrete Laplacian
  timestamp: 18 December, 2017
