---
benchmark:
  id: 1b
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '200000'
    wall_time: '7464'
- name: memory_usage
  values:
  - unit: KB
    value: '308224'
- description: free energy data
  format:
    parse:
      free_energy: number
      sim_time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.sim_time
    type: formula
  type: line
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/free-energy-9pt.csv
- description: microstructure at t=0
  name: image_000
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-000000.png
- description: microstructure at t=5,000
  name: image_005
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-005000.png
- description: microstructure at t=10,000
  name: image_010
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-010000.png
- description: microstructure at t=20,000
  name: image_020
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-020000.png
- description: microstructure at t=50,000
  name: image_050
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-050000.png
- description: microstructure at t=100,000
  name: image_100
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-100000.png
- description: microstructure at t=150,000
  name: image_150
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-150000.png
- description: microstructure at t=200,000
  name: image_200
  type: image
  url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/spinodal-200000.png
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: gpu
    clock_rate: '1.48'
    cores: '1792'
    cpu_architecture: x86_64
    nodes: 1
    parallel_model: threaded
  implementation:
    container_url: ''
    name: custom
    repo:
      url: https://github.com/usnistgov/hiperc
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
  simulation_name: hiperc_cuda
  summary: HiPerC spinodal decomposition result using CUDA on a Tesla P100
  timestamp: 18 December, 2017
