---
_id: f62c6ff0-9c0f-11e8-995f-5178b29ab3fb
benchmark:
  id: 2a
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '100000'
    wall_time: '7086'
- name: memory_usage
  values:
  - unit: KB
    value: '1643671'
- description: Data for benchmark 2a
  format:
    parse:
      time: number
      total_energy: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.total_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/ed1650b9e20c7245120d3a048591ab32/raw/da53a794aae48640820e6bfd31bcfcca0facc55a/MOOSE_FH_2a.csv
date: 1533845300
metadata:
  author:
    email: fhilty@ufl.edu
    first: Floyd
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: '0'
    cores: '8'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/2a.i
      version: a001b86
  summary: Results for benchmark 2a
  timestamp: 9 August, 2018
