---
_id: 24956860-ccad-11e8-ae72-2f6995b7b44d
metadata:
  author:
    first: Ian
    last: Greenquist
    email: ikg5018@psu.edu
    github_id: itgreenquist
  timestamp: '19 March, 2018'
  summary: Benchmark Problem 1b
  implementation:
    name: moose
    repo:
      url: 'https://github.com/itgreenquist/moose/tree/benchmark'
      version: fa4420c
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: serial
    clock_rate: '0'
    cores: '8'
    nodes: '1'
benchmark:
  id: 1b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '2280'
        sim_time: '983023'
  - name: memory_usage
    values:
      - unit: KB
        value: '1241620'
  - name: free_energy
    url: >-
      https://raw.githubusercontent.com/itgreenquist/moose/benchmark/benchmark_uploads/prob_1/b_energy.csv
    format:
      type: csv
      parse:
        time: number
        total_energy: number
    description: Simulation data for benchmark 1b
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_energy
        as: 'y'
date: 1539190465
