---
_id: 3a137180-168e-11e8-b1fd-f167a257a673
approved: false
benchmark:
  id: 7b
  version: '0'
data:
- name: run_time
  values:
  - sim_time: '0'
    wall_time: '0'
- name: memory_usage
  values:
  - unit: KB
    value: '0'
- description: Error vs Cost plot
  format:
    parse:
      cost: number
      error: number
    type: csv
  name: cost
  transform:
  - as: x
    expr: datum.error
    type: formula
  - as: y
    expr: datum.cost
    type: formula
  type: line
  url: https://f000.backblazeb2.com/file/pfhub-sjd/bm7b_quad.csv
- description: Error vs Time plot
  format:
    parse:
      error: number
      wall_time: number
    type: csv
  name: time
  transform:
  - as: x
    expr: datum.error
    type: formula
  - as: y
    expr: datum.wall_time
    type: formula
  type: line
  url: https://f000.backblazeb2.com/file/pfhub-sjd/bm7b_quad.csv
date: 1519166075
metadata:
  author:
    email: stvdwtt@umich.edu
    first: Stephen
    github_id: stvdwtt
    last: DeWitt
  hardware:
    acc_architecture: none
    clock_rate: '3.5'
    cores: '6'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: distributed
  implementation:
    container_url: ''
    name: prisms
    repo:
      url: https://github.com/prisms-center/phaseField/tree/master/applications/CHiMaD_benchmark7
      version: 7cdde5a5c48ef64b6a9d2454836ce3c784f222a5
  summary: Initial run of Benchmark 7 using PRISMS-PF. This simulation uses quadratic
    elements (3rd order accurate in space) and forward Euler time stepping (1st order
    in time).
  timestamp: 1 February, 2018
title: Comment
