---
_id: a7858cb0-9c0f-11e8-995f-5178b29ab3fb
benchmark:
  id: 1d
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '1000000'
    wall_time: '5560'
- name: memory_usage
  values:
  - unit: KB
    value: '2025888'
- description: Data for benchmark 1d
  format:
    parse:
      time: number
      total_energy: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.total_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/ed6debf7e2c3c5aae26d5372de29f1cf/raw/9704c6761d88b91d5e0fcb3e2e611b7e147aa628/MOOSE_FH_1d.csv
date: 1533845168
metadata:
  author:
    email: fhilty@ufl.edu
    first: Floyd
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: '0'
    cores: '8'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/1d.i
      version: a001b86
  summary: Results for benchmark 1d
  timestamp: 9 August, 2018
