---
_id: 3cdb3390-c5d3-11e8-a0f6-d181ad34b031
metadata:
  author:
    first: Daniel
    last: Schwen
    email: daniel.schwen@inl.gov
    github_id: dschwen
  timestamp: '2 October, 2018'
  summary: Results for Benchmark problem 3a
  implementation:
    name: moose
    repo:
      url: 'https://github.com/dschwen/moose/tree/benchmark'
      version: c641f401591bf67f76b2bb1a59168488aa5712d6
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '2.7'
    cores: '6'
    nodes: '1'
benchmark:
  id: 3a
  version: '1'
data:
  - name: efficiency
    transform:
    - as: x
      expr: datum.time_ratio
      type: formula
    - as: y
      expr: datum.memory
      type: formula
    values:
    - memory: 4263472.0
      time_ratio: 0.0449946666
  - name: run_time
    values:
      - wall_time: '67.492'
        sim_time: '1500'
  - name: memory_usage
    values:
      - unit: KB
        value: '4264096'
  - name: free_energy
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/pfhub_3a.1_out.csv
    format:
      type: csv
      parse:
        time: number
        free_energy: number
    description: Free energy versus time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.free_energy
        as: 'y'
  - name: solid_fraction
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/pfhub_3a.1_out.csv
    format:
      type: csv
      parse:
        time: number
        solid_fraction: number
    description: Solid fraction versus time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.solid_fraction
        as: 'y'
  - name: tip_position
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/pfhub_3a.1_out.csv
    format:
      type: csv
      parse:
        time: number
        tip_pos: number
    description: Tip position versus time
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.tip_pos
        as: 'y'
  - name: phase_field_1500
    url: >-
      https://raw.githubusercontent.com/dschwen/moose/benchmark/modules/phase_field/examples/benchmarks/contour_1500.csv
    format:
      type: csv
      parse:
        x: number
        'y': number
    description: Zero contour at t=1500s
    type: line
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
date: 1538437168
