---
_id: 800067c0-5dc9-11e8-a869-ff152a244da0
benchmark:
  id: 3a
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '1500'
    wall_time: '360000'
- name: memory_usage
  values:
  - unit: KB
    value: '100000'
- name: efficiency
  transform:
  - as: x
    expr: "1. / datum.time_ratio"
    type: formula
  - as: y
    expr: datum.memory
    type: formula
  values:
  - memory: 100000
    time_ratio: 0.0041666
- description: Free energy versus time
  format:
    parse:
      Free_Energy: number
      Time: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.Time
    type: formula
  - as: y
    expr: datum.Free_Energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/962278d3e5a881a74bc14f86e4e2bf52/raw/ebb1a0e3b7622a3a9292a4a8352871a3a83d5e5b/data.csv
- description: Solid fraction versus time
  format:
    parse:
      Solid_Area_Fraction: number
      Time: number
    type: csv
  name: solid_fraction
  transform:
  - as: x
    expr: datum.Time
    type: formula
  - as: y
    expr: datum.Solid_Area_Fraction
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/962278d3e5a881a74bc14f86e4e2bf52/raw/ebb1a0e3b7622a3a9292a4a8352871a3a83d5e5b/data.csv
- description: Tip position versus time
  format:
    parse:
      Time: number
      Tip_Position: number
    type: csv
  name: tip_position
  transform:
  - as: x
    expr: datum.Time
    type: formula
  - as: y
    expr: datum.Tip_Position
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/962278d3e5a881a74bc14f86e4e2bf52/raw/ebb1a0e3b7622a3a9292a4a8352871a3a83d5e5b/data.csv
date: 1526998065
metadata:
  author:
    email: andrembc10@gmail.com
    first: 'Andre '
    github_id: andrembcosta
    last: M. B. Costa
  hardware:
    acc_architecture: none
    clock_rate: '2.9'
    cores: '1'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: custom
    repo:
      url: https://github.com/andrembcosta/1st-Order-SI-3a
      version: 928c69a
  summary: Solution to the benchmark problem 3a. For spatial discretization, adaptive
    meshes of P1 finite elements were used (PF and temperature meshes were different).
    For time discretization, a first order, semi-implicit scheme was tested. The time
    step was 0.01.
  timestamp: 15 May, 2018
tags:
- comment-subscription
timestamp: 1526998065
