---
_id: 1a23e680-26fa-11e8-afc0-57350dddc52f
benchmark:
  id: 7a
  version: '0'
data:
- name: run_time
  values:
  - sim_time: '0'
    wall_time: '0'
- name: memory_usage
  values:
  - unit: KB
    value: '0'
- description: error vs meshsize with explicit double-well representation, fixed timestep=1e-4
  format:
    parse:
      dx: number
      error: number
    type: csv
  name: spatial
  transform:
  - as: x
    expr: datum.dx
    type: formula
  - as: y
    expr: datum.error
    type: formula
  type: line
  url: https://materialsdata.nist.gov/bitstream/handle/11256/960/meshsize_explicitDW.csv?sequence=1&isAllowed=y
- description: error vs time step with explicit double-well representation, fixed
    grid spacing=0.00125
  format:
    parse:
      dt_exact: number
      error: number
    type: csv
  name: temporal
  transform:
  - as: x
    expr: datum.dt_exact
    type: formula
  - as: y
    expr: datum.error
    type: formula
  type: line
  url: https://materialsdata.nist.gov/bitstream/handle/11256/960/timestep_explicitDW.csv?sequence=2&isAllowed=y
date: 1520971626
metadata:
  author:
    email: guyer@nist.gov
    first: Jonathan
    github_id: guyer
    last: Guyer
  hardware:
    acc_architecture: none
    clock_rate: '1.4'
    cores: '16'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: distributed
  implementation:
    container_url: ''
    name: fipy
    repo:
      url: https://github.com/guyer/CHiMaDPhaseFieldVI
      version: adc0b2e992386335d01cb4f6ce9924bf3fceb115
  summary: FiPy MMS solution using explicit representation of double-well
  timestamp: 7 March, 2018
tags:
- comment-subscription
