---
_id: c37ba430-9c10-11e8-995f-5178b29ab3fb
benchmark:
  id: 2d
  version: '1'
data:
- name: run_time
  values:
  - sim_time: '100000'
    wall_time: '36195'
- name: memory_usage
  values:
  - unit: KB
    value: '5404979'
- description: Data for benchmark 2d
  format:
    parse:
      time: number
      total_energy: number
    type: csv
  name: free_energy
  transform:
  - as: x
    expr: datum.time
    type: formula
  - as: y
    expr: datum.total_energy
    type: formula
  type: line
  url: https://gist.githubusercontent.com/FHilty/28416774cdb0401c3b901c59350215b2/raw/7acad7bc794ba7b00f6fcc9f87c269ab9265cb9a/MOOSE_FH_2d.csv
date: 1533845645
metadata:
  author:
    email: fhilty@ufl.edu
    first: Floyd
    github_id: FHilty
    last: Hilty
  hardware:
    acc_architecture: none
    clock_rate: '0'
    cores: '8'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: serial
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/FHilty/Benchmarks/blob/master/2d.i
      version: a001b86
  summary: Results for benchmark 2d
  timestamp: 9 August, 2018
