---
_id: ef44e4d0-e401-11e8-8d83-dfd41e9d7292
metadata:
  author:
    first: Ivan
    last: Yashchuk
    email: ivan.yashchuk@vtt.fi
    github_id: IvanYashchuk
  timestamp: '9 November, 2018'
  summary: PF Hub benchmark 1d with FEniCS on the cluster.
  implementation:
    name: fenics
    repo:
      url: 'https://bitbucket.org/fenics-project/dolfin/'
      version: bec9fa53e5900a0dce28653cf193db5fac58255e
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: distributed
    clock_rate: '2.6'
    cores: '24'
    nodes: '1'
benchmark:
  id: 1d
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '1532'
        sim_time: '1087113.5'
  - name: memory_usage
    values:
      - unit: KB
        value: '5221368'
  - name: free_energy
    url: >-
      https://gist.githubusercontent.com/IvanYashchuk/1d7e096590a3c23f08b129e5004bcc28/raw/ecb5bdf60c84bf993d2cfa3715ae59d4b744b466/1d_sphere_noflux_out.csv
    format:
      type: csv
      parse:
        time: number
        total_free_energy: number
    description: total_free_energy_fenics_1d_ivan
    type: line
    transform:
      - type: formula
        expr: datum.time
        as: x
      - type: formula
        expr: datum.total_free_energy
        as: 'y'
date: 1541755759
