---
# Used for workflows that are required to run after a pull request
# closes.
name: pullrequest-close
on:
  pull_request:
    types: [closed]
jobs:
  pullrequest:
    runs-on: ubuntu-latest
    steps:
      - name: save-pr
        env:
          PR_NUMBER: ${{ github.event.number }}
          LOGIN: ${{ github.event.pull_request.user.login }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo $LOGIN > ./pr/login
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/
