---
name: surge
on:
  workflow_run:
    workflows:
      - pullrequest
    types:
      - in_progress
jobs:
  surge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:

      - uses: actions/checkout@v2.3.4

      - run: echo ${{ context.payload.workflow.run_id  }}

      - name: download
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ context.payload.workflow.run_id }}
          workflow_conclusion: success
          path: pr/
          name: pr_number

      - run: ls -R

      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          name: pfhub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - env:
          SURGE_LOGIN: "${{ secrets.SURGE_LOGIN }}"
          SURGE_TOKEN: "${{ secrets.SURGE_TOKEN }}"
          DOMAIN: random-cat-${{ github.event.number }}.surge.sh
        run: |
          nix-shell shell-surge.nix --command " \
            rm -rf ./_site && \
            jekyll build && \
            surge --project _site --domain ${DOMAIN}/pfhub \
          "
