---
name: surge
on:
  workflow_run:
    workflows:
      - pullrequest
    types:
      - completed
jobs:
  surge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:

      - uses: actions/checkout@v2.3.4

      - run: echo ${{ github.event.workflow_run.id }}

      - name: download
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: pr_number

      - run: echo "PRNUM=$(cat pr_number)" >> $GITHUB_ENV

      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          name: pfhub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      # Can't use pfhub sub domain here so need to change baseurl:
      # 'pfhub' to baseurl: ''. jekyll build no longer takes a
      # --baseurl arugment.
      - run: >
          sed -i "2s/.*/baseurl: ''/" _config.yml

      - env:
          SURGE_LOGIN: "${{ secrets.SURGE_LOGIN }}"
          #SURGE_LOGIN: "daniel.wheeler@nist.gov"
          SURGE_TOKEN: "${{ secrets.SURGE_TOKEN }}"
          #SURGE_TOKEN: "fcab9043c16e76c558d16bf6dc380f79"
          DOMAIN: random-cat-${{ env.PRNUM }}.surge.sh
        run: |
          nix-shell shell-surge.nix --command " \
            rm -rf ./_site && \
            jekyll build && \
            surge --project _site --domain ${DOMAIN} \
          "
