name: Test PFHub Package
on: [push, pull_request]
jobs:
  pfhub-nix-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          name: pfhub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - run: cd _data/pfhub
      - working-directory: ./_data/pfhub
        run: nix-shell --pure --command "py.test --cov-fail-under=100"
