name: PFHub Upload
on:
  issues:
    types: [labeled, edited]
jobs:
  pfhub-upload:
    if: ${{ github.event.label.name == 'upload' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/upload.yml
      - run: echo '${{ contains(github.event.issue.labels.*.name, "upload" }}'
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > upload.json
      - run: echo "SIMNAME=$(yq '.short_name' upload.json)" >> $GITHUB_ENV
      - run: echo "AUTHOR=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
      - run: |
          cat upload.json | yq -P | yq eval-all '
            select(fileIndex=0).benchmark.id = select(fileIndex=1).benchmark_id |
            select(fileIndex=0).metadata.implementation.repo.url = select(fileIndex=1).repo |
            select(fileIndex=0).metadata.summary = select(fileIndex=1).summary |
            select(fileIndex=0).metadata.implementation.name = select(fileIndex=1).code
          ' _data/blank.yaml - | yq -s '"file_" + $index'
      - run: mkdir -p _data/simulations/${{ env.SIMNAME }}
      - run: mv file_0.yml _data/simulations/${{ env.SIMNAME }}/meta.yaml
      - run: rm upload.json file_1.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "upload: ${{ env.SIMNAME }}"
          title: "upload: ${{ env.SIMNAME }}"
          body: "adding upload from issue #${{ github.event.issue.number }}"
          branch: upload_${{ env.SIMNAME }}_${{ github.event.issue.number }}
          token: ${{ secrets.PFHUB_UPLOAD_USER }}
          delete-branch: true
          author: ${{ env.AUTHOR }} <${{ env.AUTHOR }}@users.noreply.github.com>
