name: PFHub Upload
on:
  issues:
    types: [labeled, edited]
jobs:
  pfhub-upload:
    if: ${{ contains(github.event.issue.labels.*.name, 'upload') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/upload.yml
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > upload.json
      - run: jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' upload.json >> $GITHUB_ENV
      - run: echo "AUTHOR=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
      - run: echo "METAPATH=_data/simulations/${{ env.short_name }}/meta.yaml" >> $GITHUB_ENV
      - run: mkdir -p _data/simulations/${{ env.short_name }}
      - name: Fill out meta.yaml
        uses: nowactions/envsubst@v1
        with:
          input: ./_data/meta_template.yaml@v1
          output: ${{ env.METAPATH }}
        env:
          BENCHMARK_ID: ${{ env.benchmark_id }}
          GITHUB_ID: ${{ env.AUTHOR }}
          REPO_URL: ${{ env.repo }}
          SUMMARY: ${{ env.summary }}
          CODE_NAME: ${{ env.code }}
      #      - run: envsubst
      #      - run: |
      #          cat upload.json | yq -P | yq eval-all '
      #            select(fileIndex=0).benchmark.id = select(fileIndex=1).benchmark_id |
      #            select(fileIndex=0).metadata.implementation.repo.url = select(fileIndex=1).repo |
      #            select(fileIndex=0).metadata.summary = select(fileIndex=1).summary |
      #            select(fileIndex=0).metadata.implementation.name = select(fileIndex=1).code
      #          ' _data/blank.yaml - | yq -s '"file_" + $index'
      #      - run: mkdir -p _data/simulations/${{ env.short_name }}
      # - run: mv file_0.yml ${{ env.METAPATH }}
      - run: yq -i -P ${{ env.METAPATH }}
      - run: yq -i '. += "${{ env.METAPATH }}"' _data/simulation_list.yaml
      - run: rm upload.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: create-pr
        with:
          commit-message: "upload: ${{ env.short_name }}"
          title: "upload: ${{ env.short_name }}"
          body: "adding upload from issue #${{ github.event.issue.number }}"
          branch: upload_${{ env.SIMNAME }}_${{ github.event.issue.number }}
          token: ${{ secrets.PFHUB_UPLOAD_USER }}
          delete-branch: true
          author: ${{ env.AUTHOR }} <${{ env.AUTHOR }}@users.noreply.github.com>
      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        with:
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.PFHUB_UPLOAD_USER }}
          body: >-
            Thanks for the upload! Your submission has opened
            pull-request #${{ steps.create-pr.outputs.pull-request-number }}.
            Please follow up there. Wait for the build processes to
            complete and then follow the posted comments.
