name: PFHub Upload
on:
  issues:
    types: [opened]
jobs:
  pfhub-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/upload.yml
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > upload.json
      - run: |
          yq eval-all '
            select(fileIndex=0).benchmark.id = select(fileIndex=1).benchmark_id |
            select(fileIndex=0).metadata.implementation.repo.url = select(fileIndex=1).repo
          ' _data/blank.yaml upload.yaml > out.yaml
      - run: yq -s '"file_" + $index' out.yaml
      - run: echo file_0.yml
